//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLDFishStallAccounts.Model.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceItem
    {
        public int ID { get; set; }
        public int FK_ID_PurchaseInvoice { get; set; }
        public int FK_ID_Fish { get; set; }
        public double Quantity { get; set; }
        public double Rate { get; set; }
        public double Total { get; set; }
    
        public virtual Fish Fish { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
    }
}
